version: "3"

services: 
    database:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./database_data:/var/lib/mysql
        networks: 
            - webnumer
        restart: always
    php:
        depends_on: 
            - database
        build: 
            dockerfile: Dockerfile
            context: ./server
        ports: 
            - 8080:80
        volumes: 
            - ./server:/var/www/html
        restart: always
        networks: 
            - webnumer
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        environment: 
            PMA_ARBITRARY: 1
        networks:
            - webnumer
        restart: always
        ports:
            - 8888:80  
    myreactapp:
        depends_on: 
            - database
            - php
        build: 
            dockerfile: Dockerfile
            context: ./client
        ports: 
            - 3000:3000
        restart: always
        networks: 
            - webnumer
   

volumes:
    database_data:
networks: 
    webnumer: 